#define GCID_UNASSIGNED						"<non assegnato>"
#define GCID_SEPARATOR						" o "
#define GCID_RESUMEGAME						"Riprendi partita"
#define GCID_RESUMEGAME_TIP					"Per continuare la partita che stavi giocando"
#define GCID_NEWGAME						"Nuova partita"
#define GCID_NEWGAME_TIP					"Per cominciare una partita dall'inizio"
#define GCID_SELECTLEVEL					"SELEZIONE LIVELLO DI DIFFICOLTÀ"
#define GCID_NORMAL							"Fuggitivo"
#define GCID_NORMAL_TIP						"Gioca - le modalità più difficili e quella Ultimo respiro si sbloccheranno solo dopo aver completato il livello Fuggitivo"
#define GCID_NIGHTMARE						"A fuoco lento"
#define GCID_NIGHTMARE_TIP					"Preparati alla prossima sfida - supera questa modalità per affrontare il livello Killer"
#define GCID_HELL							"Killer"
#define GCID_HELL_TIP						"La sfida finale"
#define GCID_TIMEDMODE						"Ultimo respiro"
#define GCID_TIMEDMODE_TIP					"La pressione è al massimo: avrai un tempo limitato per completare ogni livello"
#define GCID_STARTTUTORIAL					"Tutorial"
#define GCID_STARTTUTORIAL_TIP				"Carica il livello tutorial per imparare i fondamenti di gioco"
#define GCID_LOAD							"Carica"
#define GCID_LOAD_TIP						"Mostra l'elenco delle partite salvate"
#define GCID_LOADGAME						"CARICA PARTITA"
#define GCID_EMPTY_LOAD						"<vuoto>"
#define GCID_EMPTY_LOAD_TIP					"Per caricare la partita da questa posizione"
#define GCID_SAVE							"Salva"
#define GCID_SAVE_TIP						"Mostra l'elenco delle posizioni disponibili"
#define GCID_SAVEGAME						"SALVA PARTITA"
#define GCID_EMPTY_SAVE						"<vuoto>"
#define GCID_EMPTY_SAVE_TIP					"Per salvare la partita in questa posizione"
#define GCID_OPTIONS						"Opzioni"
#define GCID_OPTIONS_TIP					"Per modificare i comandi, le impostazioni video, audio e di gioco"
#define GCID_OPTIONSU						"OPZIONI"
#define	GCID_CONTROLS						"Comandi"
#define GCID_CONTROLS_TIP					"Per modificare i comandi di movimento e combattimento"
#define GCID_CONTROLSU						"COMANDI"
#define GCID_MOVEMENT						"Movimento"
#define GCID_MOVEMENT_TIP					"Per modificare i comandi di movimento"
#define GCID_CHANGEMOVEMENT					"TASTI DI MOVIMENTO"
#define GCID_FORWARD						"Avanti -"
#define GCID_FORWARD_TIP					"Premi Canc per annullare / Per cambiare il tasto di movimento in avanti"
#define GCID_FORWARD_CHANGE_TIP				"Premi il nuovo tasto primario o secondario di movimento in avanti / ESC per annullare"
#define GCID_BACKWARD						"Indietro -"
#define GCID_BACKWARD_TIP					"Premi Canc per annullare / Per cambiare il tasto di movimento all'indietro"
#define GCID_BACKWARD_CHANGE_TIP			"Premi il nuovo tasto primario o secondario di movimento all'indietro / ESC per annullare"
#define GCID_STRAFELEFT						"Spost. laterale a sinistra -"
#define GCID_STRAFELEFT_TIP					"Premi Canc per annullare / Per cambiare il tasto di spostamento laterale a sinistra"
#define GCID_STRAFELEFT_CHANGE_TIP			"Premi il nuovo tasto primario o secondario di spostamento laterale a sinistra /ESC per annullare"
#define GCID_STRAFERIGHT					"Spost. laterale a destra -"
#define GCID_STRAFERIGHT_TIP					"Premi Canc per annullare / Per cambiare il tasto di spostamento laterale a destra"
#define GCID_STRAFERIGHT_CHANGE_TIP			"Premi il nuovo tasto primario o secondario di spostamento laterale a destra / ESC per annullare"
#define GCID_CROUCH							"Abbassarsi -"
#define GCID_CROUCH_TIP						"Premi Canc per annullare / Per cambiare il tasto per abbassarsi"
#define GCID_CROUCH_CHANGE_TIP				"Premi il nuovo tasto primario o secondario per abbassarsi / ESC per annullare"
#define GCID_JUMP							"Salto -"
#define GCID_JUMP_TIP						"Premi Canc per annullare / Per cambiare il tasto di salto"
#define GCID_JUMP_CHANGE_TIP				"Premi il nuovo tasto primario o secondario di salto / ESC per annullare"
#define GCID_ACTIVATE						"Usa/Zoom -"
#define GCID_ACTIVATE_TIP					"Premi Canc per annullare / Per cambiare il tasto Usa/Zoom"
#define GCID_ACTIVATE_CHANGE_TIP			"Premi il nuovo tasto primario o secondario per Usa/Zoom / ESC per annullare"
#define GCID_USEPAINKILLER					"Usa antidolorifici -"
#define GCID_USEPAINKILLER_TIP				"Premi Canc per annullare / Per cambiare il tasto di uso degli antidolorifici"
#define GCID_USEPAINKILLER_CHANGE_TIP		"Premi il nuovo tasto primario o secondario di uso degli antidolorifici / ESC per annullare"
#define GCID_BULLETTIME						"Bullet Time -"
#define GCID_BULLETTIME_TIP					"Premi Canc per annullare / Per cambiare il tasto Bullet Time"
#define GCID_BULLETTIME_CHANGE_TIP			"Premi il nuovo tasto primario o secondario Bullet Time / ESC per annullare"
#define GCID_SLOWMOTION						"Solo Bullet Time -"
#define GCID_SLOWMOTION_TIP					"Premi Canc per annullare / Per cambiare il tasto di solo Bullet Time (niente sparo in volo)"
#define GCID_SLOWMOTION_CHANGE_TIP			"Premi il nuovo tasto primario o secondario di solo Bullet Time (niente sparo in volo) / ESC per annullare"
#define GCID_DODGEMODIFIER					"Solo sparo in volo -"
#define GCID_DODGEMODIFIER_TIP				"Premi Canc per annullare / Per cambiare il tasto di solo sparo in volo (niente Bullet Time)"
#define GCID_DODGEMODIFIER_CHANGE_TIP		"Premi il nuovo tasto primario o secondario di solo sparo in volo (niente Bullet Time) / ESC per annullare"
#define GCID_PAUSEGAME						"Pausa -"
#define GCID_PAUSEGAME_TIP					"Premi Canc per annullare / Per cambiare il tasto di pausa"
#define GCID_PAUSEGAME_CHANGE_TIP			"Premi il nuovo tasto primario o secondario di pausa / ESC per annullare"
#define GCID_COMBAT							"Combattimento"
#define GCID_COMBAT_TIP						"Per modificare i comandi di combattimento"
#define GCID_CHANGECOMBAT					"TASTI DI COMBATTIMENTO"
#define GCID_SHOOT							"Fuoco -"
#define GCID_SHOOT_TIP						"Premi Canc per annullare / Per modificare il tasto di fuoco"
#define GCID_SHOOT_CHANGE_TIP				"Premi il nuovo tasto primario o secondario di fuoco / ESC per annullare"
#define GCID_RELOAD							"Ricarica -"
#define GCID_RELOAD_TIP						"Premi Canc per annullare / Per modificare il tasto di ricarica"
#define GCID_RELOAD_CHANGE_TIP				"Premi il nuovo tasto primario o secondario di ricarica / ESC per annullare"
#define GCID_NEXTWEAPON						"Arma successiva -"
#define GCID_NEXTWEAPON_TIP					"Premi Canc per annullare / Per modificare il tasto di selezione dell'arma successiva"
#define GCID_NEXTWEAPON_CHANGE_TIP			"Premi il nuovo tasto primario o secondario di selezione dell'arma successiva / ESC per annullare"
#define GCID_PREVIOUSWEAPON					"Arma precedente -"
#define GCID_PREVIOUSWEAPON_TIP				"Premi Canc per annullare / Per modificare il tasto di selezione dell'arma precedente"
#define GCID_PREVIOUSWEAPON_CHANGE_TIP		"Premi il nuovo tasto primario o secondario dell'arma precedente / ESC per annullare"
#define GCID_SELECTBESTWEAPON				"Selezione arma migliore -"
#define GCID_SELECTBESTWEAPON_TIP			"Premi Canc per annullare / Per modificare il tasto di selezione dell'arma migliore"
#define GCID_SELECTBESTWEAPON_CHANGE_TIP	"Premi il nuovo tasto primario o secondario di selezione dell'arma migliore / ESC per annullare"
#define GCID_MELEE							"Armi bianche -"
#define GCID_MELEE_TIP						"Premi Canc per annullare / Per modificare il tasto di selezione delle armi bianche"
#define GCID_MELEE_CHANGE_TIP				"Premi il nuovo tasto primario o secondario di selezione delle armi bianche / ESC per annullare"
#define GCID_HANDGUNS						"Pistole -"
#define GCID_HANDGUNS_TIP					"Premi Canc per annullare / Per modificare il tasto di selezione delle pistole"
#define GCID_HANDGUNS_CHANGE_TIP			"Premi il nuovo tasto primario o secondario di selezione delle pistole / ESC per annullare"
#define GCID_SHOTGUNS						"Fucili -"
#define GCID_SHOTGUNS_TIP					"Premi Canc per annullare / Per modificare il tasto di selezione dei fucili"
#define GCID_SHOTGUNS_CHANGE_TIP			"Premi il nuovo tasto primario o secondario di selezione dei fucili / ESC per annullare"
#define GCID_MACHINEGUNS					"Armi automatiche -"
#define GCID_MACHINEGUNS_TIP				"Premi Canc per annullare / Per modificare il tasto di selezione delle armi automatiche"
#define GCID_MACHINEGUNS_CHANGE_TIP			"Premi il nuovo tasto primario o secondario di selezione delle armi automatiche / ESC per annullare"
#define GCID_THROWABLE						"Armi da lancio -"
#define GCID_THROWABLE_TIP					"Premi Canc per annullare / Per modificare il tasto di selezione delle armi da lancio"
#define GCID_THROWABLE_CHANGE_TIP			"Premi il nuovo tasto primario o secondario di selezione delle armi da lancio / ESC per annullare"
#define GCID_SNIPER							"Fucile di precisione -"
#define GCID_SNIPER_TIP						"Premi Canc per annullare / Per modificare il tasto di selezione del fucile di precisione"
#define GCID_SNIPER_CHANGE_TIP				"Premi il nuovo tasto primario o secondario di selezione del fucile di precisione / ESC per annullare"
#define GCID_MOUSESETTINGS					"Impostazioni mouse"
#define GCID_MOUSESETTINGS_TIP				"Per modificare le impostazioni del mouse"
#define GCID_MOUSESETTINGSU					"IMPOSTAZIONI MOUSE"
#define GCID_AIMINGHSPEED					"Vel. puntamento orrizzontale "
#define GCID_AIMINGHSPEED_TIP				"Usa i tasti cursore o il mouse per modificare la velocità di puntamento orizzontale"
#define GCID_AIMINGVSPEED					"Vel. puntamento verticale "
#define GCID_AIMINGVSPEED_TIP				"Usa i tasti cursore o il mouse per modificare la velocità di puntamento verticale"
#define GCID_INVERTMOUSE					"Inverti mouse"
#define GCID_INVERTMOUSE_TIP				"Per invertire il movimento di puntamento verticale del mouse"
#define GCID_INVERTMOUSEWHEEL				"Inverti rotella mouse"
#define GCID_INVERTMOUSEWHEEL_TIP			"Per invertire lo scorrimento delle arme tramite la rotella del mouse"
#define GCID_RESTOREDEFAULTS				"Ripristina predefiniti"
#define GCID_RESTOREDEFAULTS_TIP			"Per ripristinare le impostazioni predefinite"
#define GCID_GENERIC						"Gioco"
#define GCID_GENERIC_TIP					"Per modificare le opzioni di gioco"
#define GCID_GENERICU						"GIOCO"
#define GCID_SHOWCROSSHAIR					"Mostra mirino"
#define GCID_SHOWCROSSHAIR_TIP				"Per attivare la presenza del mirino su schermo"
#define GCID_ENABLEAUTOAIM					"Puntamento automatico"
#define GCID_ENABLEAUTOAIM_TIP				"Per attivare il puntamento automatico sui nemici"
#define GCID_ENABLETIPS						"Abilita suggerimenti"
#define GCID_ENABLETIPS_TIP					"Per attivare i suggerimenti durante il gioco"
#define GCID_AUTOWEAPONCHANGE					"Cambio automatico d'arma"
#define GCID_AUTOWEAPONCHANGE_TIP				"Per attivare la scelta automatica dell'arma migliore quando se ne raccoglie una nuova"
#define GCID_BULLETTIMEAID					"Abilita aiuto Bullet Time"
#define GCID_BULLETTIMEAID_TIP				"Per conservare quanto più Bullet Time possibile tramite la disabilitazione automatica in alcune situazioni di gioco"
#define GCID_READSTORY						"Leggi storia - F1"
#define GCID_READSTORY_TIP					"Ti permette di rileggere la storia fino al punto raggiunto - questo tasto non può essere cambiato"
#define GCID_SHOWOBJECTIVES					"Mostra obiettivi - F2"
#define GCID_SHOWOBJECTIVES_TIP				"Per visualizzare gli obiettivi di ciascun livello - questo tasto non può essere cambiato"
#define GCID_QUICKSAVE						"Salvataggio veloce - F5"
#define GCID_QUICKSAVE_TIP					"Salva la partita in corso nella posizione di salvataggio veloce - questo tasto non può essere cambiato"
#define GCID_QUICKLOAD						"Caricamento veloce - F9"
#define GCID_QUICKLOAD_TIP					"Carica l'ultimo salvataggio veloce - questo tasto non può essere cambiato"
#define GCID_VIDEO							"Video"
#define GCID_VIDEO_TIP						"Per modificare le impostazioni video"
#define GCID_VIDEOU							"VIDEO"
#define GCID_TEXTUREMIPMAP					"Definizione texture  "
#define GCID_TEXTUREMIPMAP_TIP				"Usa i tasti cursore o il mouse per modificare la definizione delle texture"
#define GCID_GAMMACONTROL					"Luminosità  "
#define GCID_GAMMACONTROL_TIP				"Usa i tasti cursore o il mouse per modificare la luminosità"
#define GCID_SOUND							"Audio"
#define GCID_SOUND_TIP						"Per modificare le impostazioni audio"
#define GCID_SOUNDU							"AUDIO"
#define GCID_MUSICVOLUME					"Volume musica "
#define GCID_MUSICVOLUME_TIP				"Usa i tasti cursore o il mouse per modificare il volume della musica"
#define GCID_EFFECTSVOLUME					"Volume effetti "
#define GCID_EFFECTSVOLUME_TIP				"Usa i tasti cursore o il mouse per modificare il volume degli effetti"
#define GCID_QUIT							"Esci"
#define GCID_QUIT_TIP						"Per smettere di giocare a Max Payne"
#define GCID_CREDITS						"Riconoscimenti"
#define GCID_CREDITS_TIP					"Per visualizzare i riconoscimenti"


#define	GCID_QUITJOKE01						"                                               Potevo sentire i demoni muoversi nell'oscurità..."
#define	GCID_QUITJOKE02						"                                               Le munizioni si stavano esaurendo... e loro erano ancora lì..."
#define	GCID_QUITJOKE03						"                                               Niente era stato risolto..."
#define	GCID_QUITJOKE04						"                                               Nessuno mi avrebbe potuto aiutare..."
#define	GCID_QUITJOKE05						"                                               Non ero ancora riuscito a trovare Cheryl... cosa stava accadendo?"
#define	GCID_QUITJOKE06						"                                               Le anime dei morti non mi avrebbero lasciato in pace..."
#define	GCID_QUITJOKE07						"                                               Ancora una volta, quella dannata sirena, portò con se l'oscurità..."
#define	GCID_QUITJOKE08						"                                               Gli incubi di qualcuno stavano prendendo vita..."
#define	GCID_QUITJOKE09						"                                               Il più orrendo degli incubi stava prendendo il sopravvento..."
#define	GCID_QUITJOKE10						"                                               Non potevo crederci... quale mente poteva volere tutto questo?"
#define	GCID_QUITJOKE11						"                                               L'inferno si apriva davanti a me, senza fine..."
#define	GCID_QUITJOKE12						"                                               Avevo ancora il fiato dei dannati sul collo..."
#define	GCID_QUITJOKE13						"                                               Il mio viaggio in quell'incubo senza fine non si era ancora concluso..."
#define	GCID_QUITJOKE14						"                                               I sospiri dei morti mi avrebbero tenuto sveglio..."
#define	GCID_QUITJOKE15						"                                               La pistola di Cybil era il mio unico lasciapassare..."
#define	GCID_QUITJOKE16						"                                               La città che non dorme mai mi guardava con occhi demoniaci..."
#define	GCID_QUITJOKE17						"                                               Nell'oscurità, l'inferno si diffondeva come una piaga..."
#define	GCID_QUITJOKE18						"                                               L'urlo delle sirene echeggiava nell'oscurità..."
#define	GCID_QUITJOKE19						"                                               La città di Silent Hill mi scrutava, voleva la mia anima..."
#define	GCID_QUITJOKE20						"                                               La morte passeggiava compiaciuta per le strade della città..."
#define	GCID_QUITJOKE21						"                                               Chiudendo gli occhi, potevo vederli ancora... senza vita, tra le fiamme"
#define	GCID_QUITJOKE22						"                                               Tutti gli orrendi segreti restavano nascosti nell'oscurità..."
#define	GCID_QUITJOKE23						"                                               Non potevo lasciare Cheryl in quell'incubo..."
#define	GCID_QUITJOKE24						"                                               Nell'oscurità la luce della torcia mi avrebbe fatto compagnia..."
#define	GCID_QUITJOKE25						"                                               Lo stridio della radio era come un chiodo piantato nel cervello..."

#define GCID_QUIT_YES						"                                               Ma ero troppo stanco per continuare."
#define GCID_QUIT_NO						"                                               Non potevo fermarmi. Dovevo insistere."

#define GCID_AREYOUSURE						"Sei sicuro?"
#define GCID_YES							"Sì"
#define GCID_YES_TIP						"Accetta modifiche"
#define GCID_NO								"No"
#define GCID_NO_TIP							"Annulla modifiche"
#define GCID_BACK							"Indietro"
#define GCID_BACK_TIP						"Torna alla pagina precedente"
#define GCID_QUIT_YES_TIP					"Interrompi la partita attuale e torna al desktop"
#define GCID_QUIT_NO_TIP					"Torna al menu principale"

#define SGID_LOADHUDTEXT					"Partita caricata"
#define SGID_SAVEHUDTEXT					"Partita salvata"
#define SGID_SAVELIMITEDHUDTEXT				"Partita salvata - %i salvataggi residui"
#define SGID_UNABLETOSAVEHUDTEXT			"Partita non salvata! Nessun salvataggio residuo"
#define SGID_SAVEGAMENOTFOUNDHUDTEXT		"Nessuna partita da caricare"
#define SGID_CANNOTSAVEHUDTEXT				"Impossibile salvare la partita a questo punto"
#define SGID_SAVINGFAILEDHUDTEXT			"Errore durante il salvataggio - partita non salvata"
#define	SGID_OUTOFTIME						"Hai esaurito il tempo!"

#define LNID_TUTORIAL 						"Tutorial"
#define LNID_PART1_CHAPTER1					"Parte I, Capitolo uno"
#define LNID_PART1_CHAPTER2					"Parte I, Capitolo due"
#define LNID_PART1_CHAPTER3					"Parte I, Capitolo tre"
#define LNID_PART1_CHAPTER4					"Parte I, Capitolo quattro"
#define LNID_PART1_CHAPTER5					"Parte I, Capitolo cinque"
#define LNID_PART1_CHAPTER6					"Parte I, Capitolo sei"
#define LNID_PART1_CHAPTER7					"Parte I, Capitolo sette"
#define LNID_PART1_CHAPTER8					"Parte I, Capitolo otto"
#define LNID_PART1_CHAPTER9					"Parte I, Capitolo nove"
#define LNID_PART2_PROLOGUE					"Parte II, Prologo"
#define LNID_PART2_CHAPTER1					"Parte II, Capitolo uno"
#define LNID_PART2_CHAPTER2					"Parte II, Capitolo due"
#define LNID_PART2_CHAPTER3					"Parte II, Capitolo tre"
#define LNID_PART2_CHAPTER4					"Parte II, Capitolo quattro"
#define LNID_PART2_CHAPTER5					"Parte II, Capitolo cinque"
#define LNID_PART2_CHAPTER6					"Parte II, Capitolo sei"
#define LNID_PART3_PROLOGUE					"Parte III, Prologo"
#define LNID_PART3_CHAPTER1					"Parte III, Capitolo uno"
#define LNID_PART3_CHAPTER2					"Parte III, Capitolo due"
#define LNID_PART3_CHAPTER3					"Parte III, Capitolo tre"
#define LNID_PART3_CHAPTER4					"Parte III, Capitolo quattro"
#define LNID_PART3_CHAPTER5					"Parte III, Capitolo cinque"
#define LNID_PART3_CHAPTER6					"Parte III, Capitolo sei"
#define LNID_PART3_CHAPTER7					"Parte III, Capitolo sette"
#define LNID_PART3_CHAPTER8					"Parte III, Capitolo otto"

#define LNID_END_COMBAT						"Finale segreto"

// graphic novel mode pause text is here since it's not a hud print
#define	GNID_TIP_PREVIOUS_CHAPTER			"Prossimo capitolo"
#define	GNID_TIP_PREVIOUS_PAGE				"Prossima pagina"
#define	GNID_TIP_PLAY						"Riproduci"
#define	GNID_TIP_STOP						"Stop"
#define	GNID_TIP_NEXT_PAGE					"Prossima pagina"
#define	GNID_TIP_NEXT_CHAPTER				"Prossimo capitolo"
#define	GNID_TIP_QUIT						"Ritorna al gioco"

#define GNID_PAUSE							"Pausa";
