// Crosshair attributes
#define	CROSSHAIR_CASTLENGTH			100

#define	CROSSHAIR_SIZEFRONTLIMIT		40.0
#define	CROSSHAIR_SIZEBACKLIMIT			40.0

//#define CROSSHAIR_SPHERERADIUS		0.15
#define	CROSSHAIR_SPHERERADIUS			0.01
#define	CROSSHAIR_SNIPERSPHERERADIUS		0.01

//---------------------------------------------------------------------------------------------------------------------------
// SILENT HILL MOD WEAPONS
//---------------------------------------------------------------------------------------------------------------------------

// Beretta
#define	BERETTA_CLIPSIZE			10
#define	BERETTA_POCKETSIZE			200
#define	BERETTA_SHOOTINGFREQUENCY		1.2
#define	BERETTA_MAXSHOOTINGFREQUENCY		1.201
#define	BERETTA_SLOWMOTIONMULTIPLIER		0.25
#define	BERETTA_BULLETDAMAGE			5
#define	BERETTA_BULLETSPREAD			80

// Glock 17
#define	GLOCK_CLIPSIZE				15
#define	GLOCK_SHOOTINGFREQUENCY			1.8
#define	GLOCK_MAXSHOOTINGFREQUENCY		1.801
#define	GLOCK_SLOWMOTIONMULTIPLIER		0.25

// Smith & Wesson M27
#define	M27_SHOOTINGFREQUENCY			1.2
#define	M27_MAXSHOOTINGFREQUENCY		1.201
#define	M27_SLOWMOTIONMULTIPLIER		0.25
#define	M27_BULLETDAMAGE			15
#define	M27_BULLETSPREAD			50
#define	M27_CLIPSIZE				6
#define	M27_POCKETSIZE				100

// Shotguns
#define	SHOTGUN_GENERIC_BULLETDAMAGE		6
#define	SHOTGUN_GENERIC_BULLETSPREAD		20
#define	SHOTGUN_POCKETSIZE			100

// BoomStick (SawedOff Shotgun)
#define	SAWEDSHOTGUN_SHOOTINGFREQUENCY		1.0
#define	SAWEDSHOTGUN_MAXSHOOTINGFREQUENCY	1.001
#define	SAWEDSHOTGUN_SLOWMOTIONMULTIPLIER	0.25
#define	SAWEDSHOTGUN_BULLETDAMAGE		6
#define	SAWEDSHOTGUN_BULLETSPREAD		100
#define	SAWEDSHOTGUN_CLIPSIZE			2

// Remington M870 (Sawed)
#define	PUMPSHOTGUN_SHOOTINGFREQUENCY		0.9
#define	PUMPSHOTGUN_MAXSHOOTINGFREQUENCY	0.901
#define	PUMPSHOTGUN_SLOWMOTIONMULTIPLIER	0.2
#define	PUMPSHOTGUN_BULLETDAMAGE		6
#define	PUMPSHOTGUN_BULLETSPREAD		90
#define	PUMPSHOTGUN_CLIPSIZE			5

// IMI Uzi
#define	UZI_CLIPSIZE				30
#define	UZI_POCKETSIZE				200
#define	UZI_SHOOTINGFREQUENCY			4
#define	UZI_MAXSHOOTINGFREQUENCY		4.001
#define	UZI_SLOWMOTIONMULTIPLIER		0.0
#define	UZI_BULLETDAMAGE			5
#define	UZI_BULLETSPREAD			90

// Browning BAR
#define	BAR_SHOOTINGFREQUENCY			0.9
#define	BAR_MAXSHOOTINGFREQUENCY		0.901
#define	BAR_SLOWMOTIONMULTIPLIER		0.1
#define	BAR_BULLETDAMAGE			30
#define	BAR_BULLETSPREAD			10
#define	BAR_CLIPSIZE				4
#define	BAR_POCKETSIZE				100

// HyperBlaster
#define	HYPERBLASTER_SHOOTINGFREQUENCY		6
#define	HYPERBLASTER_MAXSHOOTINGFREQUENCY	6.001
#define	HYPERBLASTER_BULLETDAMAGE		60
#define	HYPERBLASTER_BULLETSPREAD		20
#define	HYPERBLASTER_CLIPSIZE			2000
#define	HYPERBLASTER_POCKETSIZE			9999

//---------------------------------------------------------------------------------------------------------------------------
// END OF SILENT HILL MOD WEAPONS
//---------------------------------------------------------------------------------------------------------------------------

// Beretta (x2)
#define	BERETTADUAL_SHOOTINGFREQUENCY		1.2
#define	BERETTADUAL_MAXSHOOTINGFREQUENCY	1.201
#define	BERETTADUAL_SLOWMOTIONMULTIPLIER	0.25
#define	BERETTADUAL_BULLETDAMAGE		5
#define	BERETTADUAL_BULLETSPREAD		160

// Desert Eagle 50
#define	DESERTEAGLE_SHOOTINGFREQUENCY		1
#define	DESERTEAGLE_MAXSHOOTINGFREQUENCY	1.001
#define	DESERTEAGLE_SLOWMOTIONMULTIPLIER	0.25
#define	DESERTEAGLE_BULLETDAMAGE		30
#define	DESERTEAGLE_BULLETSPREAD		40
#define	DESERTEAGLE_CLIPSIZE			7
#define	DESERTEAGLE_POCKETSIZE			100

// JackHammer
#define	JACKHAMMER_SHOOTINGFREQUENCY		3
#define	JACKHAMMER_MAXSHOOTINGFREQUENCY		3.001
#define	JACKHAMMER_BULLETDAMAGE			6
#define	JACKHAMMER_BULLETSPREAD			90
#define	JACKHAMMER_CLIPSIZE			10
#define	JACKHAMMER_POCKETSIZE			100

// SMGs (SubMachineGuns)
#define	INGRAM_CLIPSIZE				30
#define	INGRAM_POCKETSIZE			200

// Ingram Mac M10
#define	INGRAM_SHOOTINGFREQUENCY		6
#define	INGRAM_MAXSHOOTINGFREQUENCY		6.001
#define	INGRAM_SLOWMOTIONMULTIPLIER		0.0
#define	INGRAM_BULLETDAMAGE			5
#define	INGRAM_BULLETSPREAD			100

// Ingram Mac M10 (x2)
#define	INGRAMDUAL_SHOOTINGFREQUENCY		6
#define	INGRAMDUAL_MAXSHOOTINGFREQUENCY		6.001
#define	INGRAMDUAL_SLOWMOTIONMULTIPLIER		0.0
#define	INGRAMDUAL_BULLETDAMAGE			5
#define	INGRAMDUAL_BULLETSPREAD			200

// Colt M4
#define	MP5_SHOOTINGFREQUENCY			6
#define	MP5_MAXSHOOTINGFREQUENCY		6.001
#define	MP5_BULLETDAMAGE			10
#define	MP5_BULLETSPREAD			30
#define	MP5_CLIPSIZE				30
#define	MP5_POCKETSIZE				100

// Sniper
#define	SNIPER_SHOOTINGFREQUENCY		0.5
#define	SNIPER_MAXSHOOTINGFREQUENCY		0.501
#define	SNIPER_BULLETDAMAGE			80
#define	SNIPER_BULLETSPREAD			5
#define	SNIPER_CLIPSIZE				6
#define	SNIPER_POCKETSIZE			100

// Molotov
#define	MOLOTOV_SHOOTINGFREQUENCY		0.5
#define	MOLOTOV_MAXSHOOTINGFREQUENCY		0.501
#define	MOLOTOV_CLIPSIZE			1
#define	MOLOTOV_POCKETSIZE			6

// Grenade
#define	GRENADE_SHOOTINGFREQUENCY		0.5
#define	GRENADE_MAXSHOOTINGFREQUENCY		0.501
#define	GRENADE_CLIPSIZE			1
#define	GRENADE_POCKETSIZE			6

// M79
#define	M79_SHOOTINGFREQUENCY			1
#define	M79_MAXSHOOTINGFREQUENCY		1.001
#define	M79_CLIPSIZE				1
#define	M79_POCKETSIZE				30
